### ISSUE TITLE
dnbc4tools 2.1.3 scATAC MACS2/IO/ScoreTrack...so: undefined symbol issue

### ISSUE THREAD

**Issue by lishuangshuang0616** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#121]
In some Linux platforms, when analyzing ATAC with dnbc4tools version 2.1.3, you may encounter an **"undefined symbol" error related to MACS2/IO/ScoreTrack...so. undefined symbol**

To resolve this issue, in the default environment.
In dnbc4tools2.1.3 directory 
```
source sourceC4.bash
pip uninstall macs2
pip install macs2==2.2.9.1
```

**Comment by ShihuiZhangsh** [comment]
Hello, I met this error and follow this solution, but encounter another error:
pip install macs2==2.2.9.1
Collecting macs2==2.2.9.1
  Using cached MACS2-2.2.9.1.tar.gz (2.0 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "/mnt/shihui/nfs_share/dnbc4tools2.1.3/external/conda/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/                                                  _in_process.py", line 353, in <module>
          main()
        File "/mnt/shihui/nfs_share/dnbc4tools2.1.3/external/conda/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/                                                  _in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/mnt/shihui/nfs_share/dnbc4tools2.1.3/external/conda/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/                                                  _in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-lrqvixza/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 333, in get_requires_for_                                                  build_wheel
          return self._get_build_requires(config_settings, requirements=[])
        File "/tmp/pip-build-env-lrqvixza/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 303, in _get_build_requir                                                  es
          self.run_setup()
        File "/tmp/pip-build-env-lrqvixza/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 521, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-lrqvixza/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 319, in run_setup
          exec(code, locals())
        File "<string>", line 17, in <module>
        File "/tmp/pip-build-env-lrqvixza/overlay/lib/python3.8/site-packages/Cython/Build/__init__.py", line 1, in <module>
          from .Dependencies import cythonize
        File "/tmp/pip-build-env-lrqvixza/overlay/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 48, in <module>
          from ..Compiler.Main import Context, CompilationOptions, default_options
        File "/tmp/pip-build-env-lrqvixza/overlay/lib/python3.8/site-packages/Cython/Compiler/Main.py", line 28, in <module>
          from .Scanning import PyrexScanner, FileSourceDescriptor
      ImportError: /tmp/pip-build-env-lrqvixza/overlay/lib/python3.8/site-packages/Cython/Compiler/Scanning.cpython-38-x86_64-linux-gnu                                                  .so: failed to map segment from shared object
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.


The log file information:
2025-01-13 17:49:25,609 - data - INFO - Executing command: /mnt/shihui/nfs_share/dnbc4tools2.1.3/external/conda/bin/macs2  callpeak  --treatment /mnt/shihui/nfs_share2/MORF_scData/ATAC_output/01.data/filter.merge.fragments.tsv.gz  --name ATAC_output  -B  --outdir /mnt/shihui/nfs_share2/MORF_scData/ATAC_output/01.data/callpeak  --format BED  --gsize hs  -q 0.01  --nomodel  --shift -75 --extsize 150  --tempdir /mnt/shihui/nfs_share2/MORF_scData/ATAC_output/log/.temp/ 
2025-01-13 17:49:28,017 - data - ERROR - Command failed with exit code 1
2025-01-13 17:49:28,017 - data - ERROR - Traceback (most recent call last):
  File "/mnt/shihui/nfs_share/dnbc4tools2.1.3/external/conda/bin/macs2", line 653, in <module>
    main()
  File "/mnt/shihui/nfs_share/dnbc4tools2.1.3/external/conda/bin/macs2", line 49, in main
    from MACS2.callpeak_cmd import run
  File "/mnt/shihui/nfs_share/dnbc4tools2.1.3/external/conda/lib/python3.8/site-packages/MACS2/callpeak_cmd.py", line 23, in <module>
    from MACS2.OptValidator import opt_validate
  File "/mnt/shihui/nfs_share/dnbc4tools2.1.3/external/conda/lib/python3.8/site-packages/MACS2/OptValidator.py", line 20, in <module>
    from MACS2.IO.Parser import BEDParser, ELANDResultParser, ELANDMultiParser, \
  File "MACS2/IO/Parser.pyx", line 25, in init MACS2.IO.Parser
  File "MACS2/IO/FixWidthTrack.pyx", line 27, in init MACS2.IO.FixWidthTrack
  File "MACS2/Pileup.pyx", line 19, in init MACS2.Pileup
  File "MACS2/IO/BedGraph.pyx", line 26, in init MACS2.IO.BedGraph
ImportError: /mnt/shihui/nfs_share/dnbc4tools2.1.3/external/conda/lib/python3.8/site-packages/MACS2/IO/ScoreTrack.cpython-38-x86_64-linux-gnu.so: undefined symbol: __log_finite

**Comment by lishuangshuang0616** [comment]
**Getting requirements to build wheel ... error**

I'm not quite sure why the dependencies can't be found during the installation. Since your system is also Linux, you might need to upgrade pip or delete the downloaded MACS2 cache.

**Comment by ShihuiZhangsh** [comment]
I solved it by installing MACS2 using conda
