### ISSUE TITLE
Column C0 does not exist in the Frame

### ISSUE THREAD

**Issue by KinesinStudioXQ** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#125]
# 运行代码
$ source ~/dnbc4tools/dnbc4tools2.1.3/sourceC4.bash
$ genome=~/dnbc4tools/GRCh38_gencode_v44_ref/
$ ~/dnbc4tools/dnbc4tools2.1.3/dnbc4tools rna run --name D2_1 \
> --cDNAfastq1 ./HRR1822706_R1.fq.gz,./HRR1822707_R1.fq.gz \
> --cDNAfastq2 ./HRR1822706_R2.fq.gz,./HRR1822707_R2.fq.gz \
> --oligofastq1 ./HRR1822708_R1.fq.gz \
> --oligofastq2 ./HRR1822708_R2.fq.gz \
> --genomeDir $genome --no_introns --threads 24

# 终端输出信息
Chemistry(darkreaction) determined in oligoR1: darkreaction
Chemistry(darkreaction) determined in oligoR2: darkreaction
Chemistry(darkreaction) determined in cDNAR1 : darkreaction

2024-11-11 20:59:45
Conduct quality control for cDNA library barcoding, perform alignment and annotation of gene regions.

2024-11-11 20:59:45
Perform quality control for oligo library barcodes.

2024-11-11 22:57:07
Calculating bead similarity and merging beads within the same droplet.
Traceback (most recent call last):
  /home/kinesin/dnbc4tools/dnbc4tools2.1.3/external/conda/bin/dnbc4tools:8 in <module>          sys.exit(main())
  /home/kinesin/dnbc4tools/dnbc4tools2.1.3/lib/python/dnbc4tools/dnbc4tools.py:110 in main      args.func(args)
  /home/kinesin/dnbc4tools/dnbc4tools2.1.3/lib/python/dnbc4tools/rna/count.py:199 in count      Count(args).run()
  /home/kinesin/dnbc4tools/dnbc4tools2.1.3/lib/python/dnbc4tools/rna/count.py:76 in run         similarity_droplet_file('%s/02.count/similarity.droplet.csv'%self.outdir,
  /home/kinesin/dnbc4tools/dnbc4tools2.1.3/lib/python/dnbc4tools/tools/utils.py:186 in wrapper  result = func(*args, **kwargs)
  combineBeads.py:71 in dnbc4tools.tools.combineBeads.similarity_droplet_file

KeyError: Column C0 does not exist in the Frame
Traceback (most recent call last):
  File "/home/kinesin/dnbc4tools/dnbc4tools2.1.3/external/conda/bin/dnbc4tools", line 8, in <module>
    sys.exit(main())
  File "/home/kinesin/dnbc4tools/dnbc4tools2.1.3/lib/python/dnbc4tools/dnbc4tools.py", line 110, in main
    args.func(args)
  File "/home/kinesin/dnbc4tools/dnbc4tools2.1.3/lib/python/dnbc4tools/rna/run.py", line 144, in run
    Runpipe(args).runpipe()
  File "/home/kinesin/dnbc4tools/dnbc4tools2.1.3/lib/python/dnbc4tools/rna/run.py", line 131, in runpipe
    start_print_cmd(pipecmd,os.path.join(self.outdir,self.name))
  File "/home/kinesin/dnbc4tools/dnbc4tools2.1.3/lib/python/dnbc4tools/tools/utils.py", line 141, in start_print_cmd
    subprocess.check_call(arg, shell=True)
  File "/home/kinesin/dnbc4tools/dnbc4tools2.1.3/external/conda/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/home/kinesin/dnbc4tools/dnbc4tools2.1.3/external/conda/bin/dnbc4tools rna count --name D2_1 --calling_method emptydrops --expectcells 3000 --threads 24 --outdir /home/kinesin/disk8t/proj2024/m11_ypj/D2_1' returned non-zero exit status 1.
Process exited with status: exit status: 1

# 运行结果与日志
$ ls D2_1/01.data/
CB_UB_count.txt  Log.out           SJ.out.tab            anno_report.csv  cDNA.barcode.counts.txt     cDNA_para  cDNAin2           oligo.barcode.counts.txt  oligo.sequencing.report.csv
Log.final.out    Log.progress.out  alignment_report.csv  beads_stat.txt   cDNA.sequencing.report.csv  cDNAin1    final_sorted.bam  oligo.reads.fq.gz         oligo_para
$ ls D2_1/02.count/
beads.barcodes.umi100.txt  similarity.all.csv  similarity.droplet.csv
$ tail D2_1/log/20241111.txt
2024-11-11 22:33:56,546 - INFO -
2024-11-11 22:33:56,546 - INFO - Read the whitelist and position config of oligo R2.
2024-11-11 22:33:56,546 - INFO -
2024-11-11 22:47:32,262 - INFO - Filter the oligo index cell barcodes in oligo R2 fastq.
2024-11-11 22:47:32,262 - INFO -
2024-11-11 22:56:42,420 - INFO - Complete the combined analysis of cDNA and oligo and generate /home/kinesin/disk8t/proj2024/m11_ypj/D2_1/D2_1/01.data/CB_UB_count.txt
2024-11-11 22:56:42,421 - INFO -
/home/kinesin/dnbc4tools/dnbc4tools2.1.3/external/conda/bin/dnbc4tools rna count --name D2_1 --calling_method emptydrops --expectcells 3000 --threads 24 --outdir /home/kinesin/disk8t/proj2024/m11_ypj/D2_1
2024-11-11 22:57:08,711 - INFO - Merge beads within the same droplet based on correlation values.
2024-11-11 22:57:08,711 - INFO -
$ cat D2_1/log/_bt_log
program exit
/home/kinesin/dnbc4tools/dnbc4tools2.1.3/lib/python/dnbc4tools/software/scStar() [0x426370]
/home/kinesin/dnbc4tools/dnbc4tools2.1.3/lib/python/dnbc4tools/software/scStar() [0x426adf]
/lib/x86_64-linux-gnu/libc.so.6(+0x468a7) [0x7f0f645378a7]
/lib/x86_64-linux-gnu/libc.so.6(on_exit+0) [0x7f0f64537a60]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xfa) [0x7f0f6451508a]
/home/kinesin/dnbc4tools/dnbc4tools2.1.3/lib/python/dnbc4tools/software/scStar() [0x40edcf]

# 数据情况
$ zcat HRR1822706_R1.fq.gz | head -n 18 | sed -n '2p;6p;10p;14p;18p'
GGCAGACCTACGCGACGAGGATTAGAAGAT
GAGATGCGTGTTATAGTAATCAATTACACG
CCGATGAGCATCGCAGCTGTCATGAAGCAC
CAGGAACGAGGGTGCAACCTTACATATCTG
AGCTCATCGCCAAGACAAGTATCTCGAGGG
$ zcat HRR1822706_R2.fq.gz | head -n 18 | sed -n '2p;6p;10p;14p;18p'
ATAGCAAAAAAAAAACTATCATCAGTGTGAACAGGCAACCTACAGAATGGGAGAAAGTTTTTGCAATCTATCCATTTGACAAAGGGCTGATATCCAGAAT
ATTCATATATGAACACTCAAAGTATTAATAATTTTGCATTGCTATTATTAATACTTTGAGTGTTCATATATGGATAGAAGAGAATGTGGTTTGGGATTTG
GCCAGGCTGGTCTCAAACTCCTGGCCTCAGGTGATCTGCCCATCTTGGCCTCCCAAAGTGCTGGGATTACAGGCGTGAGCCACTGCACCTGACCATGAAA
AGATGGTGGTGATGATTGCCCAACATTATGAATATTTAATACCACTGAATTGTATATACTTAAACATAGTAAATTTTGTGTTATGGGTATATTAACAGAA
GCTAGGACTATAAGCATGTGCCACTATGCCTGGATAATTTTTGTATTTTTAGTAGAGTGGGGGTTTTCCCATGTTTCCCAGGCTGGTCTCGTACTCATGT
$ zcat HRR1822707_R1.fq.gz | head -n 18 | sed -n '2p;6p;10p;14p;18p'
CTCTAAGCATGTTGTCTGACGCAAGAGGGA
GCTAAGCTTCGATAATGAGTTCGTCACCAA
TGTAATCCATCCTTCCTGGTGGTTAAAGTA
CCGACTTGCATGATGGACCTCCAGCACGAA
TCTGTAGGCCAGCTGCTGAACCAAATAACA
$ zcat HRR1822707_R2.fq.gz | head -n 18 | sed -n '2p;6p;10p;14p;18p'
ATAATCCTAACCAAAGATATGAAAGCTCTCTCTAATGGACACTATAAAATATTATGCAAGAAACTGAAGAAGGCAATCATAAGTTAAAAAATATTTTATA
ATGGGCCACGGTATCATACTCAAACTAGGAATGGGTTTCTCATAACCCAAAGAAACCTGCCAGCTCTTGCGCCTTTTTTTGCTGTACGAGAATGTATACG
GTTCATTCTTTCTTTTCTTTTCTTTTCCTCTTTCTTTCTTTCTTTCTTGCCAGGGTATTTATTTATTTATTTATTTAGAGCCAGGGCCTCCCTCTGTCAC
CTTTGGGTGGCTGAGGCAGCAGGATCCTTTGAGCCCAGGAGTTCGAGACCAGCCTGGCCAACATAGCAAGACCTCTTCTCTACTAAAAATAAAAATTAGC
TATAACCAAGCATAATATAGCAAGGACTAACCCCAACACAGGCATGCTCATAAGGAAAGGTTAAAAAAAGTAAAAGGAACTCGGCAAATCTTACCCCGCC
$ zcat HRR1822708_R1.fq.gz | head -n 18 | sed -n '2p;6p;10p;14p;18p'
AAGGTTGGCCGGCACGACGT
GAAGGCAAGCTCCAATCTCG
CTCACTGTAGTGGTTAGGCA
CAGCTAATGCCATACATGAG
TCCGACCGTAGCCGCAATAG
$ zcat HRR1822708_R2.fq.gz | head -n 18 | sed -n '2p;6p;10p;14p;18p'
CCTAATGCTCTCTTGGAGACAGTTCCTGTC
ATCGAAAGGTCGAGCAGGTTCTCACCTAAG
ATGAGGAGAGACTAACCGTATAACAGCCAA
TTCCTTAAAATCGATATCCTTAACAGCCAA
AACTGCAATGCATGATGCATACGGCGAGGC

请问这是什么情况？

**Comment by lishuangshuang0616** [comment]
能否截图看下`01.data`  `02.count`目录内文件大小，`ls -lh `
然后截图看下`01.data/beads_stat.txt`的前10行

**Comment by KinesinStudioXQ** [comment]
谢谢回复，02.count目录下的文件都是空的，具体结果如下：
ls -lh 01.data/
总用量 43G
-rw-rw-r-- 1 kinesin kinesin  160 11月 11 22:07 alignment_report.csv
-rw-rw-r-- 1 kinesin kinesin  310 11月 11 22:07 anno_report.csv
-rw-rw-r-- 1 kinesin kinesin  69M 11月 11 22:07 beads_stat.txt
-rw-rw-r-- 1 kinesin kinesin 1.4G 11月 11 22:56 CB_UB_count.txt
-rw-rw-r-- 1 kinesin kinesin  56M 11月 11 21:44 cDNA.barcode.counts.txt
-rw-rw-r-- 1 kinesin kinesin  126 11月 11 20:59 cDNAin1
-rw-rw-r-- 1 kinesin kinesin  126 11月 11 20:59 cDNAin2
-rw-rw-r-- 1 kinesin kinesin  525 11月 11 20:59 cDNA_para
-rw-rw-r-- 1 kinesin kinesin  387 11月 11 21:44 cDNA.sequencing.report.csv
-rw-rw-r-- 1 kinesin kinesin  21G 11月 11 22:33 final_sorted.bam
-rw-rw-r-- 1 kinesin kinesin 2.0K 11月 11 21:49 Log.final.out
-rw-rw-r-- 1 kinesin kinesin  12K 11月 11 21:49 Log.out
-rw-rw-r-- 1 kinesin kinesin 5.5K 11月 11 21:49 Log.progress.out
-rw-rw-r-- 1 kinesin kinesin  56M 11月 11 21:27 oligo.barcode.counts.txt
-rw-rw-r-- 1 kinesin kinesin  522 11月 11 20:59 oligo_para
-rw-rw-r-- 1 kinesin kinesin  21G 11月 11 21:28 oligo.reads.fq.gz
-rw-rw-r-- 1 kinesin kinesin  377 11月 11 21:27 oligo.sequencing.report.csv
-rw-rw-r-- 1 kinesin kinesin  35M 11月 11 21:49 SJ.out.tab

ls -lh 02.count/
总用量 0
-rw-rw-r-- 1 kinesin kinesin 0 11月 11 22:57 beads.barcodes.umi100.txt
-rw-rw-r-- 1 kinesin kinesin 0 11月 11 22:57 similarity.all.csv
-rw-rw-r-- 1 kinesin kinesin 0 11月 11 22:57 similarity.droplet.csv

head 01.data/beads_stat.txt
BARCODE Raw     UB      GN      GnReads
TGCAGTGGTACTCAGAGGCG    549074  8       3       60
CTAAGATATTCGACTACTCT    513847  12      4       69
CCGCAGGAGCGCAATGCGAG    432709  9       4       35
CAACATATAATAACTTCATG    390699  14      4       123
AGAGACTCCGAGTTCACTCA    374348  16      3       146
TCCTAACAATGCAAGCTGCC    334128  6       3       15
GACCAGAATATGAGGCGGCC    328932  7       5       57
CTGATACTTCGACCTGCGCG    319409  1       1       1
TCAACGAACCTGTCTCATCC    306835  0       0       0

**Comment by lishuangshuang0616** [comment]
![image](https://github.com/user-attachments/assets/94ae243f-bce4-43c6-a413-35bde957333b)
这个不对劲啊，那么多reads就这么点umi，是gtf有问题吗，检查一下原因看看
https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/blob/version2.0/doc/pipeline/scRNA.md

**Comment by KinesinStudioXQ** [comment]
重新构建参考基因组后运行正常了，非常感谢！
另外有个小建议：dnbc4tools rna run的genomeDir参数用于指定参考基因组的路径，但是程序运行的时候又根据ref.json中信息去找参考基因组。这样的设置会导致移动、重命名和分享参考基因组后运行报错，没有注意到这个细节又很难发现并解决问题。不知道这点以后是否可以调整一下？

**Comment by lishuangshuang0616** [comment]
嗯嗯，主要是程序需要比较多的信息，单纯的star index只能用于比对，还需要gtf文件去注释，线粒体chr和gene去分析含量。atac那块就更多的信息了，所以需要一个json文件记录提供程序去识别。
