### ISSUE TITLE
Provision to use custom regex for mitochondrial genes in non-human organism

### ISSUE THREAD

**Issue by Rohit-Satyam** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#132]
Hi @MGI-tech-bioinformatics 

We have noticed that in the alignment summary file for our organism Plasmodium have o% of mitochondrial reads. This might be because of the default regex used for human to filter the mitochondrial reads. Out mitochondrial genes starts with `PF3D7_MIT` eg: `PF3D7_MIT02300`. Can you make an argument `--mito-regex` that can be used to specify custom mitochondrial regular expression?

**Comment by lishuangshuang0616** [comment]
<img width="969" alt="image" src="https://github.com/user-attachments/assets/766a00b3-2eed-45b0-9c96-9730b88b3966">
You need to provide mitochondrial chromosomes when building the library

**Comment by Rohit-Satyam** [comment]
Awesome @lishuangshuang0616. I will try that. Meanwhile I ran into an error:

```bash
Perform quality control for oligo library barcodes.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/subudhak/dnbc4tools2.1.3/external/conda/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/subudhak/dnbc4tools2.1.3/lib/python/dnbc4tools/tools/utils.py", line 131, in logging_call
    raise e
  File "/home/subudhak/dnbc4tools2.1.3/lib/python/dnbc4tools/tools/utils.py", line 126, in logging_call
    output = subprocess.check_output(popenargs, shell=True, stderr=subprocess.STDOUT, universal_newlines=True)
  File "/home/subudhak/dnbc4tools2.1.3/external/conda/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/subudhak/dnbc4tools2.1.3/external/conda/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/subudhak/dnbc4tools2.1.3/lib/python/dnbc4tools/software/scStar --outSAMattributes singleCell --outSAMtype BAM Unsorted --genomeDir /phd/project4/mgi_V350267882/resources/tgme49 --outFileNamePrefix ../01.data/ --stParaFile /phd/project4/mgi_V350267882/alignment/tgme49_Ctrl/01.data/cDNA_para --outSAMmode NoQS --runThreadN 200 --limitOutSJcollapsed 10000000 --limitIObufferSize 1500000000']' died with <Signals.SIGKILL: 9>.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/subudhak/dnbc4tools2.1.3/external/conda/bin/dnbc4tools", line 8, in <module>
    sys.exit(main())
  File "/home/subudhak/dnbc4tools2.1.3/lib/python/dnbc4tools/dnbc4tools.py", line 110, in main
    args.func(args)
  File "/home/subudhak/dnbc4tools2.1.3/lib/python/dnbc4tools/rna/data.py", line 158, in data
    Data(args).run()
  File "/home/subudhak/dnbc4tools2.1.3/lib/python/dnbc4tools/rna/data.py", line 109, in run
    process_libraries(
  File "/home/subudhak/dnbc4tools2.1.3/lib/python/dnbc4tools/tools/utils.py", line 186, in wrapper
    result = func(*args, **kwargs)
  File "staranno.py", line 174, in dnbc4tools.rna.src.staranno.process_libraries
  File "staranno.py", line 187, in dnbc4tools.rna.src.staranno.process_libraries
  File "staranno.py", line 182, in dnbc4tools.rna.src.staranno.process_libraries
  File "/home/subudhak/dnbc4tools2.1.3/external/conda/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
subprocess.CalledProcessError: Command '['/home/subudhak/dnbc4tools2.1.3/lib/python/dnbc4tools/software/scStar --outSAMattributes singleCell --outSAMtype BAM Unsorted --genomeDir /phd/project4/mgi_V350267882/resources/tgme49 --outFileNamePrefix ../01.data/ --stParaFile /phd/project4/mgi_V350267882/alignment/tgme49_Ctrl/01.data/cDNA_para --outSAMmode NoQS --runThreadN 200 --limitOutSJcollapsed 10000000 --limitIObufferSize 1500000000']' died with <Signals.SIGKILL: 9>.
Traceback (most recent call last):
  File "/home/subudhak/dnbc4tools2.1.3/external/conda/bin/dnbc4tools", line 8, in <module>
    sys.exit(main())
  File "/home/subudhak/dnbc4tools2.1.3/lib/python/dnbc4tools/dnbc4tools.py", line 110, in main
    args.func(args)
  File "/home/subudhak/dnbc4tools2.1.3/lib/python/dnbc4tools/rna/run.py", line 144, in run
    Runpipe(args).runpipe()
  File "/home/subudhak/dnbc4tools2.1.3/lib/python/dnbc4tools/rna/run.py", line 131, in runpipe
    start_print_cmd(pipecmd,os.path.join(self.outdir,self.name))
  File "/home/subudhak/dnbc4tools2.1.3/lib/python/dnbc4tools/tools/utils.py", line 141, in start_print_cmd
    subprocess.check_call(arg, shell=True)
  File "/home/subudhak/dnbc4tools2.1.3/external/conda/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/home/subudhak/dnbc4tools2.1.3/external/conda/bin/dnbc4tools rna data --cDNAfastq1 /home/subudhak/phddata/project4/mgi_V350267882/raw_data/V350267882_L01_3_1.fq.gz,/home/subudhak/phddata/project4/mgi_V350267882/raw_data/V350267882_L02_3_1.fq.gz,/home/subudhak/phddata/project4/mgi_V350267882/raw_data/V350267882_L03_3_1.fq.gz,/home/subudhak/phddata/project4/mgi_V350267882/raw_data/V350267882_L04_3_1.fq.gz --cDNAfastq2 /home/subudhak/phddata/project4/mgi_V350267882/raw_data/V350267882_L01_3_2.fq.gz,/home/subudhak/phddata/project4/mgi_V350267882/raw_data/V350267882_L02_3_2.fq.gz,/home/subudhak/phddata/project4/mgi_V350267882/raw_data/V350267882_L03_3_2.fq.gz,/home/subudhak/phddata/project4/mgi_V350267882/raw_data/V350267882_L04_3_2.fq.gz --oligofastq1 /home/subudhak/phddata/project4/mgi_V350267882/raw_data/V350267882_L01_11_1.fq.gz,/home/subudhak/phddata/project4/mgi_V350267882/raw_data/V350267882_L02_11_1.fq.gz,/home/subudhak/phddata/project4/mgi_V350267882/raw_data/V350267882_L03_11_1.fq.gz,/home/subudhak/phddata/project4/mgi_V350267882/raw_data/V350267882_L04_11_1.fq.gz --oligofastq2 /home/subudhak/phddata/project4/mgi_V350267882/raw_data/V350267882_L01_11_2.fq.gz,/home/subudhak/phddata/project4/mgi_V350267882/raw_data/V350267882_L02_11_2.fq.gz,/home/subudhak/phddata/project4/mgi_V350267882/raw_data/V350267882_L03_11_2.fq.gz,/home/subudhak/phddata/project4/mgi_V350267882/raw_data/V350267882_L04_11_2.fq.gz --threads 200 --name tgme49_Ctrl --chemistry auto --darkreaction auto --outdir /phd/project4/mgi_V350267882/alignment --genomeDir /phd/project4/mgi_V350267882/resources/tgme49 --gtf /phd/project4/mgi_V350267882/resources/tgme49/tgme49.genes.filter.gtf --chrMT None' returned non-zero exit status 1.
Process exited with status: exit status: 1
```

**Comment by Rohit-Satyam** [comment]
Decreasing the number of threads to 120 helped and error disappeared.

**Comment by lishuangshuang0616** [comment]
Ah, why are there so many threads? Haha.
