### ISSUE TITLE
单细胞分析时自动退出报错

### ISSUE THREAD

**Issue by xiaoxiaoniao666** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#139]
工程师您好，
我在最近的分析过程中，遇到了一个奇怪的报错，之前的都没问题。线程给了50个，内存200G，但运行过程中自动退出并报错

Traceback (most recent call last):
  File "/public1/home/a8s000127/miniforge3/envs/dnbc4tools/bin/dnbc4tools", line 8, in <module>
    sys.exit(main())
  File "/public1/home/a8s000127/miniforge3/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/dnbc4tools.py", line 110, in main
    args.func(args)
  File "/public1/home/a8s000127/miniforge3/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/rna/data.py", line 169, in data
    Data(args).run()
  File "/public1/home/a8s000127/miniforge3/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/rna/data.py", line 157, in run
    oligo_combine_pl(f"{__root_dir__}/config/cellbarcode/oligo_type.json",
  File "/public1/home/a8s000127/miniforge3/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/tools/utils.py", line 183, in wrapper
    result = func(*args, **kwargs)
  File "oligo_filter.py", line 355, in dnbc4tools.rna.src.oligo_filter.oligo_combine_pl
  File "oligo_filter.py", line 244, in dnbc4tools.rna.src.oligo_filter.OligoCombiner.polars_CBUB
  File "/public1/home/a8s000127/miniforge3/envs/dnbc4tools/lib/python3.8/site-packages/polars/utils/deprecation.py", line 100, in wrapper
    return function(*args, **kwargs)
  File "/public1/home/a8s000127/miniforge3/envs/dnbc4tools/lib/python3.8/site-packages/polars/io/csv/functions.py", line 369, in read_csv
    df = pl.DataFrame._read_csv(
  File "/public1/home/a8s000127/miniforge3/envs/dnbc4tools/lib/python3.8/site-packages/polars/dataframe/frame.py", line 784, in _read_csv
    self._df = PyDataFrame.read_csv(
polars.exceptions.NoDataError: empty CSV
Traceback (most recent call last):
  File "/public1/home/a8s000127/miniforge3/envs/dnbc4tools/bin/dnbc4tools", line 8, in <module>
    sys.exit(main())
  File "/public1/home/a8s000127/miniforge3/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/dnbc4tools.py", line 110, in main
    args.func(args)
  File "/public1/home/a8s000127/miniforge3/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/rna/run.py", line 144, in run
    Runpipe(args).runpipe()
  File "/public1/home/a8s000127/miniforge3/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/rna/run.py", line 131, in runpipe
    start_print_cmd(pipecmd,os.path.join(self.outdir,self.name))
  File "/public1/home/a8s000127/miniforge3/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/tools/utils.py", line 138, in start_print_cmd
    subprocess.check_call(arg, shell=True)
  File "/public1/home/a8s000127/miniforge3/envs/dnbc4tools/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/public1/home/a8s000127/miniforge3/envs/dnbc4tools/bin/dnbc4tools rna data --cDNAfastq1 /public1/home/a8s000003/share/data/HRKF_000_2409243C/PM-2409243-138-2/Rawdata/LC-P-HYS/LC-P-HYS_raw_R1.fq.gz --cDNAfastq2 /public1/home/a8s000003/share/data/HRKF_000_2409243C/PM-2409243-138-2/Rawdata/LC-P-HYS/LC-P-HYS_raw_R2.fq.gz --oligofastq1 /public1/home/a8s000003/share/data/HRKF_000_2409243C/PM-2409243-138-2/Rawdata/LC-P-HYS_Oligo/LC-P-HYS_Oligo_raw_R1.fq.gz --oligofastq2 /public1/home/a8s000003/share/data/HRKF_000_2409243C/PM-2409243-138-2/Rawdata/LC-P-HYS_Oligo/LC-P-HYS_Oligo_raw_R2.fq.gz --threads 50 --name LC-P-HYS --chemistry auto --darkreaction auto --outdir /public1/home/a8s000003/share/analysis/fenggangyi/danxibao/problem/01.cleandata --genomeDir /public1/home/a8s000003/share/analysis/fenggangyi/refrence/scrna/human --gtf /public1/home/a8s000003/share/analysis/fenggangyi/refrence/scrna/human/gencode.v32.primary_assembly.annotation.gtf --chrMT chrM' returned non-zero exit status 1.

**Comment by lishuangshuang0616** [comment]
参考 #93 #51 
可以看下注释的结果中是否注释上了，01.data/alignment_report.csv，01.data/anno_report.csv
或者看上01.data/beads_stat.txt是否umi数量很低。

**Comment by xiaoxiaoniao666** [comment]
![Uploading 1734336372753.jpg…]()

**Comment by xiaoxiaoniao666** [comment]
![Uploading 1734336398096.jpg…]()

**Comment by xiaoxiaoniao666** [comment]
$ cat alignment_report.csv
Raw reads,463314822
Mapped reads,463314822 (100.00%)
Plus strand,267843218
Minus strand,195471604
Mitochondria ratio,2.14%
Mapping quality corrected reads,6883074

$ cat anno_report.csv 
Reads Mapped to Genome (Map Quality >= 0),100.0%
Reads Mapped to Exonic Regions,76.3%
Reads Mapped to Intronic Regions,8.9%
Reads Mapped to both Exonic and Intronic Regions,0.0%
Reads Mapped Antisense to Gene,8.6%
Reads Mapped to Intergenic Regions,14.8%
Reads Mapped to Gene but Failed to Interpret Type,0.0%

这是两个文件

**Comment by lishuangshuang0616** [comment]
看下ls -lh 01.data，
我看下CB_UB文件的大小

**Comment by xiaoxiaoniao666** [comment]
ls -lh 01.data/
total 108G
-rw-r--r-- 1 a8s000127 a8s000003  40G Dec 16 15:05 Aligned.out.bam
-rw-r--r-- 1 a8s000127 a8s000003  163 Dec 16 16:10 alignment_report.csv
-rw-r--r-- 1 a8s000127 a8s000003  310 Dec 16 16:10 anno_report.csv
-rw-r--r-- 1 a8s000127 a8s000003  66M Dec 16 16:10 beads_stat.txt
-rw-r--r-- 1 a8s000127 a8s000003  52M Dec 16 15:05 cDNA.barcode.counts.txt
-rw-r--r-- 1 a8s000127 a8s000003  109 Dec 16 14:44 cDNAin1
-rw-r--r-- 1 a8s000127 a8s000003  109 Dec 16 14:44 cDNAin2
-rw-r--r-- 1 a8s000127 a8s000003  743 Dec 16 14:44 cDNA_para
-rw-r--r-- 1 a8s000127 a8s000003  385 Dec 16 15:05 cDNA.sequencing.report.csv
-rw-r--r-- 1 a8s000127 a8s000003  43G Dec 16 16:10 final.bam
-rw-r--r-- 1 a8s000127 a8s000003  25G Dec 16 13:00 final_sorted.bam
-rw-r--r-- 1 a8s000127 a8s000003 1.1G Dec 16 16:12 final_sorted.bam.tmp.0000.bam
-rw-r--r-- 1 a8s000127 a8s000003 2.0K Dec 16 15:05 Log.final.out
-rw-r--r-- 1 a8s000127 a8s000003  14K Dec 16 15:05 Log.out
-rw-r--r-- 1 a8s000127 a8s000003 2.6K Dec 16 15:05 Log.progress.out
-rw-r--r-- 1 a8s000127 a8s000003    0 Dec 16 14:46 oligo.barcode.counts.txt
-rw-r--r-- 1 a8s000127 a8s000003  793 Dec 16 14:44 oligo_para
-rw-r--r-- 1 a8s000127 a8s000003 1000 Dec 16 14:46 oligo.reads.fq.gz
-rw-r--r-- 1 a8s000127 a8s000003  354 Dec 16 14:46 oligo.sequencing.report.csv
-rw-r--r-- 1 a8s000127 a8s000003  20M Dec 16 15:05 SJ.out.tab
drwxr-xr-x 2 a8s000127 a8s000003 4.0K Dec 16 13:00 temp
-rw-r--r-- 1 a8s000127 a8s000003    0 Dec 16 13:00 total_reads.xls

**Comment by xiaoxiaoniao666** [comment]
我把线程设置到了10  正在运行

**Comment by lishuangshuang0616** [comment]
> 我把线程设置到了10 正在运行

Is it solved?

**Comment by Ckenen** [comment]
我运行的时候也出现了“polars.exceptions.NoDataError: empty CSV”。

我有5个样品，2个成功了，3个总是失败。通过比较分析发现失败的样品的oligo的R1的第一个碱基都是“N”（100%），而且质量很差（Q=0）；而成功的样品虽然也有很多N（<100%），但是也有部份其他碱基。

另外，失败样品里面的01.data/oligo.sequencing.report.csv里面的数值是nan，oligo.barcode.counts.txt和oligo.reads.fq.gz文件是空的，没有输出CB_UB_count.txt文件。

然后我将oligo R1和cDNA R1的第一个碱基强行改为T，质量调高，流程就运行成功了。cDNA的R1可能不需要改，但是我没测试过；碱基质量可能不需要改，但是我没测试过；核心就是改oligo R1的第一个碱基。

修改脚本如下：
```
#!/usr/bin/env python
import sys

for i, line in enumerate(sys.stdin):
    j = i % 4
    if j == 1:
        line = "T" + line[1:]
    elif j == 3:
        line = "D" + line[1:]
    sys.stdout.write(line)
```
