### ISSUE TITLE
DNBC4tools 主程序运行时报错

### ISSUE THREAD

**Issue by luyz1998** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#15]
作者您好!我在使用DNBC4tools （2.0.7）主程序run时，运行到生成raw_matrix目录时产生报错：
Traceback (most recent call last):
  File "/gpfs/home/luyz/biosoft/miniconda3/envs/DNBC4tools/bin/DNBC4tools", line 8, in <module>sys.exit(main())
  File "/gpfs/home/luyz/biosoft/miniconda3/envs/DNBC4tools/lib/python3.8/site-packages/DNBC4tools/DNBC4tools.py", line 43, in mainargs.func(args)
  File "/gpfs/home/luyz/biosoft/miniconda3/envs/DNBC4tools/lib/python3.8/site-packages/DNBC4tools/tools/data.py", line 47, in data Data(args).run()
  File "/gpfs/home/luyz/biosoft/miniconda3/envs/DNBC4tools/lib/python3.8/site-packages/DNBC4tools/tools/data.py", line 42, in run
    logging_call(raw_matrix_cmd,'data',self.outdir)
  File "/gpfs/home/luyz/biosoft/miniconda3/envs/DNBC4tools/lib/python3.8/site-packages/DNBC4tools/tools/utils.py", line 50, in logging_call check_call(popenargs,shell=True)
  File "/gpfs/home/luyz/biosoft/miniconda3/envs/DNBC4tools/lib/python3.8/subprocess.py", line 364, in check_call raise CalledProcessError(retcode, cmd) subprocess.CalledProcessError: Command '/gpfs/home/luyz/biosoft/miniconda3/envs/DNBC4tools/lib/python3.8/site-packages/DNBC4tools/soft/PISA count -@ 32 -cb CB -anno-tag GN -umi UB -outdir /gpfs/home/luyz/work/singlecell/midaiwu/dnbflow/STM/stomach/01.data/raw_matrix /gpfs/home/luyz/work/singlecell/midaiwu/dnbflow/STM/stomach/01.data/final_sorted.bam' returned non-zero exit status 1.
多个样本运行都出现了这个报错，请问是什么原因呢？

**Comment by lishuangshuang0616** [comment]
Can you take a screenshot of the 01.data directory, I need to confirm that there is no problem with the steps before the PISA count @luyz1998

**Comment by luyz1998** [comment]
![image](https://user-images.githubusercontent.com/110225569/217486322-7a8eaf8a-2009-4b79-8da9-3673a36c3969.png)

**Comment by lishuangshuang0616** [comment]
From the screenshots, it seems that there is no problem with the previous analysis, but why the time for mapping and annotation is not long, but the time for the samtools sort to generate **final_sorted.bam** is indeed very long, which is quite strange. You can use **samtools quickcheck** to check the integrity of **final_sorted.bam**. Is there any other errors before the error message? @luyz1998

**Comment by luyz1998** [comment]
samtools quickcheck的结果没问题，不知道是不是我们服务器的一些故障导致的个人账号下一些软件的损坏（有其他软件因损坏不能正常运行），我正在尝试重装软件之后再运行任务，如果还是同样报错再与您联系！非常感谢！

**Comment by lishuangshuang0616** [comment]
好的，也可以单独跑下**PISA count**那个步骤来看下是否还会报错。 @luyz1998

**Comment by luyz1998** [comment]
![image](https://user-images.githubusercontent.com/110225569/217753507-337a92bd-226c-4232-9e42-6e4a7bc8da45.png)
重装软件后单独运行PISA count产生了不同的报错，显示如上。

**Comment by lishuangshuang0616** [comment]
看下anno_report.csv

**Comment by luyz1998** [comment]
![image](https://user-images.githubusercontent.com/110225569/217762984-88117b1a-c299-4811-8e77-02a0b692dc8e.png)

**Comment by lishuangshuang0616** [comment]
看来你的gtf文件有点问题 @luyz1998

**Comment by luyz1998** [comment]
非常感谢回答！已找到问题所在！
