### ISSUE TITLE
DNBC4tools主程序报错

### ISSUE THREAD

**Issue by gogozyz** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#16]
感谢团队辛苦工作和付出。
目前遇到一主程序报错，烦请帮忙分析解决，报错代码如下：
2023-03-03 11:13:07,903 - count - INFO - Promgram start...
2023-03-03 11:13:07,903 - count - INFO - /home/gogozyz/anaconda3/envs/DNBC4tools/bin/python /home/gogozyz/anaconda3/envs/DNBC4tools/lib/python3.8/site-packages/DNBC4tools/rna/cellMerge.py --indir /home/gogozyz/storagezyz/scRNA-seq/test/02.count --name test
Traceback (most recent call last):
  File "/home/gogozyz/anaconda3/envs/DNBC4tools/lib/python3.8/site-packages/DNBC4tools/rna/cellMerge.py", line 103, in <module>
    from plotnine import *
  File "/home/gogozyz/anaconda3/envs/DNBC4tools/lib/python3.8/site-packages/plotnine/__init__.py", line 1, in <module>
    from .qplot import qplot            # noqa: F401
  File "/home/gogozyz/anaconda3/envs/DNBC4tools/lib/python3.8/site-packages/plotnine/qplot.py", line 9, in <module>
    from .ggplot import ggplot
  File "/home/gogozyz/anaconda3/envs/DNBC4tools/lib/python3.8/site-packages/plotnine/ggplot.py", line 20, in <module>
    from .facets import facet_null
  File "/home/gogozyz/anaconda3/envs/DNBC4tools/lib/python3.8/site-packages/plotnine/facets/__init__.py", line 1, in <module>
    from .facet_grid import facet_grid
  File "/home/gogozyz/anaconda3/envs/DNBC4tools/lib/python3.8/site-packages/plotnine/facets/facet_grid.py", line 6, in <module>
    from .facet import facet, layout_null, combine_vars, add_missing_facets
  File "/home/gogozyz/anaconda3/envs/DNBC4tools/lib/python3.8/site-packages/plotnine/facets/facet.py", line 13, in <module>
    from ..scales.scales import Scales
  File "/home/gogozyz/anaconda3/envs/DNBC4tools/lib/python3.8/site-packages/plotnine/scales/__init__.py", line 83, in <module>
    from .limits import xlim, ylim, lims, expand_limits
  File "/home/gogozyz/anaconda3/envs/DNBC4tools/lib/python3.8/site-packages/plotnine/scales/limits.py", line 8, in <module>
    from ..geoms import geom_blank
  File "/home/gogozyz/anaconda3/envs/DNBC4tools/lib/python3.8/site-packages/plotnine/geoms/__init__.py", line 6, in <module>
    from .geom_abline import geom_abline
  File "/home/gogozyz/anaconda3/envs/DNBC4tools/lib/python3.8/site-packages/plotnine/geoms/geom_abline.py", line 9, in <module>
    from .geom import geom
  File "/home/gogozyz/anaconda3/envs/DNBC4tools/lib/python3.8/site-packages/plotnine/geoms/geom.py", line 3, in <module>
    from ..stats.stat import stat
  File "/home/gogozyz/anaconda3/envs/DNBC4tools/lib/python3.8/site-packages/plotnine/stats/__init__.py", line 6, in <module>
    from .stat_density import stat_density
  File "/home/gogozyz/anaconda3/envs/DNBC4tools/lib/python3.8/site-packages/plotnine/stats/stat_density.py", line 6, in <module>
    import statsmodels.api as sm
  File "/home/gogozyz/.local/lib/python3.8/site-packages/statsmodels/api.py", line 123, in <module>
    from .tsa import api as tsa
  File "/home/gogozyz/.local/lib/python3.8/site-packages/statsmodels/tsa/api.py", line 74, in <module>
    from .filters import api as filters, bk_filter, cf_filter, hp_filter
  File "/home/gogozyz/.local/lib/python3.8/site-packages/statsmodels/tsa/filters/api.py", line 6, in <module>
    from .filtertools import miso_lfilter, convolution_filter, recursive_filter
  File "/home/gogozyz/.local/lib/python3.8/site-packages/statsmodels/tsa/filters/filtertools.py", line 18, in <module>
    from scipy.signal.signaltools import _centered as trim_centered
ImportError: cannot import name '_centered' from 'scipy.signal.signaltools' (/home/gogozyz/anaconda3/envs/DNBC4tools/lib/python3.8/site-packages/scipy/signal/signaltools.py)
Traceback (most recent call last):
  File "/home/gogozyz/anaconda3/envs/DNBC4tools/bin/DNBC4tools", line 8, in <module>
    sys.exit(main())
  File "/home/gogozyz/anaconda3/envs/DNBC4tools/lib/python3.8/site-packages/DNBC4tools/DNBC4tools.py", line 43, in main
    args.func(args)
  File "/home/gogozyz/anaconda3/envs/DNBC4tools/lib/python3.8/site-packages/DNBC4tools/tools/count.py", line 71, in count
    Count(args).run()
  File "/home/gogozyz/anaconda3/envs/DNBC4tools/lib/python3.8/site-packages/DNBC4tools/tools/count.py", line 59, in run
    logging_call(CellMerge_cmd,'count',self.outdir)
  File "/home/gogozyz/anaconda3/envs/DNBC4tools/lib/python3.8/site-packages/DNBC4tools/tools/utils.py", line 50, in logging_call
    check_call(popenargs,shell=True)
  File "/home/gogozyz/anaconda3/envs/DNBC4tools/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/home/gogozyz/anaconda3/envs/DNBC4tools/bin/python /home/gogozyz/anaconda3/envs/DNBC4tools/lib/python3.8/site-packages/DNBC4tools/rna/cellMerge.py --indir /home/gogozyz/storagezyz/scRNA-seq/test/02.count --name test' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/home/gogozyz/anaconda3/envs/DNBC4tools/bin/DNBC4tools", line 8, in <module>
    sys.exit(main())
  File "/home/gogozyz/anaconda3/envs/DNBC4tools/lib/python3.8/site-packages/DNBC4tools/DNBC4tools.py", line 43, in main
    args.func(args)
  File "/home/gogozyz/anaconda3/envs/DNBC4tools/lib/python3.8/site-packages/DNBC4tools/tools/run.py", line 78, in run
    Runpipe(args).runpipe()
  File "/home/gogozyz/anaconda3/envs/DNBC4tools/lib/python3.8/site-packages/DNBC4tools/tools/run.py", line 70, in runpipe
    start_print_cmd(pipecmd)
  File "/home/gogozyz/anaconda3/envs/DNBC4tools/lib/python3.8/site-packages/DNBC4tools/tools/utils.py", line 31, in start_print_cmd
    check_call(arg,shell=True)
  File "/home/gogozyz/anaconda3/envs/DNBC4tools/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'DNBC4tools count --name test --raw_matrix /home/gogozyz/storagezyz/scRNA-seq/test/01.data/raw_matrix --bam /home/gogozyz/storagezyz/scRNA-seq/test/01.data/final_sorted.bam --calling_method emptydrops --expectcells 10000 --forcecells 0 --minumi 1000 --cDNAbarcodeCount /home/gogozyz/storagezyz/scRNA-seq/test/01.data/cDNA_barcode_counts_raw.txt --Indexreads /home/gogozyz/storagezyz/scRNA-seq/test/01.data/Index_reads.fq.gz --oligobarcodeCount /home/gogozyz/storagezyz/scRNA-seq/test/01.data/Index_barcode_counts_raw.txt --thread 24 --outdir /home/gogozyz/storagezyz/scRNA-seq' returned non-zero exit status 1.

附已生成文件截图
![image](https://user-images.githubusercontent.com/91236712/222750847-ad3708df-9234-44eb-8055-28946b957f8d.png)

**Comment by lishuangshuang0616** [comment]
<img width="587" alt="1677908668478" src="https://user-images.githubusercontent.com/49019821/222878481-30078911-516c-4d51-8dc0-ad2ae06a438c.png">

Thanks for your trust and support. Judging from the error report, it seems that the process caused by your bashrc configuration uses local python package that is not in the DNBC4tools environment. You can first use 
```
export PATH=/miniconda3/envs/DNBC4tools/bin:$PATH
export LD_LIBRARY_PATH=/miniconda3/envs/DNBC4tools/lib:$LD_LIBRARY_PATH, 
```
 because your 01.data has been completed, add --process count,analysis,report to the command line to skip the data step @gogozyz
