### ISSUE TITLE
DNBCtools主程序（count）报错

### ISSUE THREAD

**Issue by yuanmaomao2023** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#24]
您好，我在使用DNBCtools进行主程序运行时，中生成filter_matrix过程中出现报错，报错内容如下：
2023-07-30 12:06:05,074 - count - INFO - Promgram start...
2023-07-30 12:06:05,074 - count - INFO - /../bin/python /../DNBC4tools/lib/python3.8/site-packages/DNBC4tools/rna/cellMerge.py --indir /../02.count --name xxx
Traceback (most recent call last):
  File "/../python3.8/site-packages/pandas/core/indexes/base.py", line 3652, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'index'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/../DNBC4tools/lib/python3.8/site-packages/DNBC4tools/rna/cellMerge.py", line 95, in <module>
    figtable['index'] = figtable['index'].astype(int)
  File "/../python3.8/site-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/../python3.8/site-packages/pandas/core/indexes/base.py", line 3654, in get_loc
    raise KeyError(key) from err
KeyError: 'index'
Traceback (most recent call last):
  File "/../DNBC4tools/bin/DNBC4tools", line 8, in <module>
    sys.exit(main())
  File "/../DNBC4tools/lib/python3.8/site-packages/DNBC4tools/DNBC4tools.py", line 43, in main
    args.func(args)
  File "/../DNBC4tools/lib/python3.8/site-packages/DNBC4tools/tools/count.py", line 71, in count
    Count(args).run()
  File "/../DNBC4tools/lib/python3.8/site-packages/DNBC4tools/tools/count.py", line 59, in run
    logging_call(CellMerge_cmd,'count',self.outdir)
  File "/../DNBC4tools/lib/python3.8/site-packages/DNBC4tools/tools/utils.py", line 50, in logging_call
    check_call(popenargs,shell=True)
  File "/../DNBC4tools/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/../DNBC4tools/bin/python /../DNBC4tools/lib/python3.8/site-packages/DNBC4tools/rna/cellMerge.py --indir /../02.count --name xx returned non-zero exit status 1.

麻烦您可以帮我看一下吗？尝试过pandas升级，但是还是出现同样的报错，冒昧打扰，非常感谢！

**Comment by lishuangshuang0616** [comment]
能截图一下你的02.count生成的目录内的文件吗？特别是combined_list.txt这个文件能否看下内容。

**Comment by yuanmaomao2023** [comment]
非常感谢能得到您的回复，
以下是我的02.count文件内容和combined.list文件具体内容






再次感谢您的回复，也很抱歉周末时间贸然打扰您，祝您生活愉快，一切顺利。
| |
袁梦丽
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年7月30日 22:07 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software] DNBCtools主程序（count）报错 (Issue #24) |

能截图一下你的02.count生成的目录内的文件吗？特别是combined_list.txt这个文件能否看下内容。

**Comment by lishuangshuang0616** [comment]
我这边看不到你发的图片
你看看是不是没传过来
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/49019821/e2785d42-3dd8-49b4-9b86-9ab3f3cdaa14)

**Comment by yuanmaomao2023** [comment]
老师您好，
我把图片放在附件里，麻烦您再帮我看一下吧。





| |
袁梦丽
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年7月31日 11:32 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software] DNBCtools主程序（count）报错 (Issue #24) |

我这边看不到你发的图片
你看看是不是没传过来

**Comment by lishuangshuang0616** [comment]
抱歉我还是没看到，你邮件和我沟通吧
lishuangshuang3@mgi-tech.com
