### ISSUE TITLE
conda环境安装dnbc4tools报错，以及dnbc4tools rna mkref报错

### ISSUE THREAD

**Issue by Xixu551** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#31]
使用conda安装dnbc4tools时出现以下冲突提示：
```
conda env create -f dnbc4tools.yaml -n dnbc4tools
```
```
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done


==> WARNING: A newer version of conda exists. <==
  current version: 23.7.2
  latest version: 23.7.4

Please update conda by running

    $ conda update -n base -c defaults conda

Or to minimize the number of packages updated during conda update use

     conda install conda=23.7.4



Downloading and Extracting Packages

Preparing transaction: ...working... done
Verifying transaction: ...working... 
SafetyError: The package for r-base located at /public/home/chenzhizhuo/anaconda3/pkgs/r-base-4.2.0-h1ae530e_0
appears to be corrupted. The path 'lib/R/doc/html/packages.html'
has an incorrect size.
  reported size: 3191 bytes
  actual size: 41503 bytes

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/linux-64::libstdcxx-ng-12.2.0-h46fd767_19, defaults/linux-64::binutils_impl_linux-64-2.38-h2a08ee3_1
  path: 'share/licenses/libstdc++/RUNTIME.LIBRARY.EXCEPTION'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/linux-64::libgomp-12.2.0-h65d4601_19, defaults/linux-64::binutils_impl_linux-64-2.38-h2a08ee3_1
  path: 'share/licenses/gcc-libs/RUNTIME.LIBRARY.EXCEPTION.gomp_copy'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/linux-64::binutils_impl_linux-64-2.38-h2a08ee3_1, conda-forge/linux-64::libgcc-ng-12.2.0-h65d4601_19
  path: 'share/info/libgomp.info'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/linux-64::binutils_impl_linux-64-2.38-h2a08ee3_1, conda-forge/linux-64::libgcc-ng-12.2.0-h65d4601_19
  path: 'share/info/libquadmath.info'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/linux-64::binutils_impl_linux-64-2.38-h2a08ee3_1, conda-forge/linux-64::libgcc-ng-12.2.0-h65d4601_19
  path: 'share/licenses/gcc-libs/RUNTIME.LIBRARY.EXCEPTION'



done
Executing transaction: ...working... 

    Installed package of scikit-learn can be accelerated using scikit-learn-intelex.
    More details are available here: https://intel.github.io/scikit-learn-intelex

    For example:

        $ conda install scikit-learn-intelex
        $ python -m sklearnex my_application.py

    

done
Installing pip dependencies: ...working... Ran pip subprocess with arguments:
['/public/home/chenzhizhuo/anaconda3/envs/dnbc4tools/bin/python', '-m', 'pip', 'install', '-U', '-r', '/public/home/chenzhizhuo/downloads/condaenv.86e07n12.requirements.txt', '--exists-action=b']
Pip subprocess output:
Collecting dnbc4tools==2.1.0
  Using cached DNBC4tools-2.1.0-py3-none-any.whl (33.2 MB)
Collecting polars==0.13.40
  Downloading polars-0.13.40-cp37-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (11.9 MB)
     鈹佲攣鈹佲攣鈹佲攣鈹佲攣鈹佲攣鈹佲攣鈹佲攣鈹佲攣鈹佲攣鈹佲攣鈹佲攣鈹佲攣鈹佲攣鈹佲攣鈹佲攣鈹佲攣鈹佲攣鈹佲攣鈹佲攣鈹佲攣 11.9/11.9 MB 1.1 MB/s eta 0:00:00
Collecting tarjan==0.2.3.2
  Downloading tarjan-0.2.3.2.tar.gz (4.1 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting typing-extensions==4.5.0
  Downloading typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Requirement already satisfied: numpy>=1.16.0 in /public/home/chenzhizhuo/anaconda3/envs/dnbc4tools/lib/python3.8/site-packages (from polars==0.13.40->-r /public/home/chenzhizhuo/downloads/condaenv.86e07n12.requirements.txt (line 2)) (1.23.5)
Building wheels for collected packages: tarjan
  Building wheel for tarjan (setup.py): started
  Building wheel for tarjan (setup.py): finished with status 'done'
  Created wheel for tarjan: filename=tarjan-0.2.3.2-py3-none-any.whl size=5131 sha256=a3482a3e2002564d868e88ef0ad53759c40252c0738832c996a9c23a6295c7bf
  Stored in directory: /public/home/chenzhizhuo/.cache/pip/wheels/a2/b3/a1/6544ff907b6c70bc6d915bed6169b372850a21bc40c0a7e0e1
Successfully built tarjan
Installing collected packages: tarjan, dnbc4tools, typing-extensions, polars
Successfully installed dnbc4tools-2.1.0 polars-0.13.40 tarjan-0.2.3.2 typing-extensions-4.5.0

done
#
# To activate this environment, use
#
#     $ conda activate dnbc4tools
#
# To deactivate an active environment, use
#
#     $ conda deactivate
```

创建参考基因组时发生如下报错：
```
dnbc4tools rna mkref --ingtf genes.filter.gtf --fasta GRCh38.primary_assembly.genome.fa --threads 1 --species Homo_sapiens
```
```
STAR verison: 2.7.2b
runMode: genomeGenerate
runThreadN: 1
limitGenomeGenerateRAM: 125000000000
genomeSAindexNbases: 14
genomeChrBinNbits: 18
genomeDir: /public/home/chenzhizhuo/utils
fasta: /public/home/chenzhizhuo/utils/GRCh38.primary_assembly.genome.fa
gtf: /public/home/chenzhizhuo/utils/genes.filter.gtf
2023-9-15  10:32:31 ..... started STAR run
Sep 15 10:32:31 ... starting to generate Genome files
Sep 15 10:33:29 ... starting to sort Suffix Array. This may take a long time...
Sep 15 10:33:43 ... sorting Suffix Array chunks and saving them to disk...
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Error code: SAW-A10400
get signal:	6
Traceback (most recent call last):
  File "/public/home/chenzhizhuo/anaconda3/envs/dnbc4tools/bin/dnbc4tools", line 8, in <module>
    sys.exit(main())
  File "/public/home/chenzhizhuo/anaconda3/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/dnbc4tools.py", line 58, in main
    args.func(args)
  File "/public/home/chenzhizhuo/anaconda3/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/rna/mkref.py", line 135, in mkref
    Ref(args).run()
  File "/public/home/chenzhizhuo/anaconda3/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/rna/mkref.py", line 130, in run
    star_index(self.fasta,self.ingtf,self.genomeDir,"%s/software/scStar"%__root_dir__,self.limitram,self.threads)
  File "/public/home/chenzhizhuo/anaconda3/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/rna/mkref.py", line 52, in star_index
    start_print_cmd(star_cmd_str)
  File "/public/home/chenzhizhuo/anaconda3/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/tools/utils.py", line 34, in start_print_cmd
    check_call(arg,shell=True)
  File "/public/home/chenzhizhuo/anaconda3/envs/dnbc4tools/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/public/home/chenzhizhuo/anaconda3/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/software/scStar --runMode genomeGenerate --runThreadN 1 --genomeDir /public/home/chenzhizhuo/utils --genomeFastaFiles /public/home/chenzhizhuo/utils/GRCh38.primary_assembly.genome.fa --sjdbGTFfile /public/home/chenzhizhuo/utils/genes.filter.gtf --sjdbOverhang 99 --limitGenomeGenerateRAM 125000000000 --genomeSAindexNbases 14 --genomeChrBinNbits 18' died with <Signals.SIGABRT: 6>.
```

**Comment by lishuangshuang0616** [comment]
创建数据库需要大的内存，从报错来看运行内存不够
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Error code: SAW-A10400
get signal:	6

**Comment by Xixu551** [comment]
> 创建数据库需要大的内存，从报错来看运行内存不够 terminate called after throwing an instance of 'std::bad_alloc' what(): std::bad_alloc Error code: SAW-A10400 get signal: 6

解决了，感谢
