### ISSUE TITLE
analysis 这一步报错 No cells found

### ISSUE THREAD

**Issue by Kellytian124** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#36]
16:58:01 Optimization finished
Error: No cells found
Execution halted
Traceback (most recent call last):
  File "/opt/conda/envs/DNBC4tools/bin/DNBC4tools", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/DNBC4tools/lib/python3.8/site-packages/DNBC4tools/DNBC4tools.py", line 43, in main
    args.func(args)
  File "/opt/conda/envs/DNBC4tools/lib/python3.8/site-packages/DNBC4tools/tools/analysis.py", line 36, in analysis
    Analysis(args).run()
  File "/opt/conda/envs/DNBC4tools/lib/python3.8/site-packages/DNBC4tools/tools/analysis.py", line 32, in run
    logging_call(qc_cmd,'analysis',self.outdir)
  File "/opt/conda/envs/DNBC4tools/lib/python3.8/site-packages/DNBC4tools/tools/utils.py", line 50, in logging_call
    check_call(popenargs,shell=True)
  File "/opt/conda/envs/DNBC4tools/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/opt/conda/envs/DNBC4tools/bin/Rscript /opt/conda/envs/DNBC4tools/lib/python3.8/site-packages/DNBC4tools/rna/QC_analysis.R -I /mgi_storage/sk/tiantian/singlecell/SC20231012_old/SC20231012_old/02.count/filter_matrix -D 20 -P 0.05 -M auto -MP 15 -F 200 -B SC20231012_old -O /mgi_storage/sk/tiantian/singlecell/SC20231012_old/SC20231012_old/03.analysis' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/opt/conda/envs/DNBC4tools/bin/DNBC4tools", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/DNBC4tools/lib/python3.8/site-packages/DNBC4tools/DNBC4tools.py", line 43, in main
    args.func(args)
  File "/opt/conda/envs/DNBC4tools/lib/python3.8/site-packages/DNBC4tools/tools/run.py", line 78, in run
    Runpipe(args).runpipe()
  File "/opt/conda/envs/DNBC4tools/lib/python3.8/site-packages/DNBC4tools/tools/run.py", line 70, in runpipe
    start_print_cmd(pipecmd)
  File "/opt/conda/envs/DNBC4tools/lib/python3.8/site-packages/DNBC4tools/tools/utils.py", line 31, in start_print_cmd
    check_call(arg,shell=True)
  File "/opt/conda/envs/DNBC4tools/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'DNBC4tools analysis --name SC20231012_old --matrix /mgi_storage/sk/tiantian/singlecell/SC20231012_old/SC20231012_old/02.count/filter_matrix --species Homo_sapiens --outdir /mgi_storage/sk/tiantian/singlecell/SC20231012_old --mtgenes auto' returned non-zero exit status 1.

请问是什么原因呢？

**Comment by lishuangshuang0616** [comment]
可以看下02.count里面cellCount_report.csv的gene数量是否过少，可能在03.analysis这步骤全部过滤掉了.
方案1，可以单独跑03.analysis这个步骤，DNBC4tools analysis然后调整部分参数来通过。
方案2，更新软件版本，后续版本这个步骤会自适应过滤。

**Comment by Kellytian124** [comment]
感谢，用第二种方案解决了！

**Comment by lishuangshuang0616** [comment]
> 感谢，用第二种方案解决了！

Glad to see the problem solved.
