### ISSUE TITLE
KeyError: 'index'

### ISSUE THREAD

**Issue by yc508** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#43]
Hello, I have encounter a new issue when running the scRNA-sequencing. And the error message is below. At first I thought it was due to  the pandas package so I updated my pandas to the latest version. However, I still got the same error. Could you help me with this issue? Thank you!

2023-12-12 02:03:46
Generating the filtered expression matrix.
Traceback (most recent call last):
  File "/home/marioyicongchen/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'index'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/marioyicongchen/nfs_share2/node_23/envs/dnbc4tools/bin/dnbc4rna", line 8, in <module>
    sys.exit(main())
  File "/mnt/marioyicongchen/nfs_share2/node_23/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/rna/dnbc4rna.py", line 38, in main
    args.func(args)
  File "/mnt/marioyicongchen/nfs_share2/node_23/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/rna/count.py", line 220, in count
    Count(args).run()
  File "/mnt/marioyicongchen/nfs_share2/node_23/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/rna/count.py", line 189, in run
    summary_count('%s/02.count/barcodeTranslate.txt'%self.outdir,
  File "/mnt/marioyicongchen/nfs_share2/node_23/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/rna/src/cellMerge.py", line 202, in summary_count
    figtable['index'] = figtable['index'].astype(int)
  File "/home/marioyicongchen/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3761, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/marioyicongchen/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 'index'
Traceback (most recent call last):
  File "/mnt/marioyicongchen/nfs_share2/node_23/envs/dnbc4tools/bin/dnbc4rna", line 8, in <module>
    sys.exit(main())
  File "/mnt/marioyicongchen/nfs_share2/node_23/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/rna/dnbc4rna.py", line 38, in main
    args.func(args)
  File "/mnt/marioyicongchen/nfs_share2/node_23/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/rna/run.py", line 105, in run
    Runpipe(args).runpipe()
  File "/mnt/marioyicongchen/nfs_share2/node_23/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/rna/run.py", line 92, in runpipe
    start_print_cmd(pipecmd,os.path.join(self.outdir,self.name))
  File "/mnt/marioyicongchen/nfs_share2/node_23/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/tools/utils.py", line 38, in start_print_cmd
    subprocess.check_call(arg, shell=True)
  File "/mnt/marioyicongchen/nfs_share2/node_23/envs/dnbc4tools/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'dnbc4rna count --name day1_mm39 --calling_method emptydrops --expectcells 3000 --forcecells 0 --minumi 1000 --threads 16 --outdir /mnt/marioyicongchen/nfs_share2/kallisto/yunfan_project/scRNA_seq/day1_scrna' returned non-zero exit status 1.

**Comment by lishuangshuang0616** [comment]
This is another version conflict. It’s strange that your environment affects the python package in dnbc4tools.

Before you can analyze:  export enviroment,
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/49019821/72082b41-a1b7-4cba-8214-270526212bc4)

 then add --process count,analysis,report
