### ISSUE TITLE
dnbc4tools run 报错

### ISSUE THREAD

**Issue by owo12138** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#58]
你好，我在运行run步骤遇到了以下问题
这是我的运行代码
`~/miniconda3/envs/dnbc4tools/bin/dnbc4tools rna run --cDNAfastq1 /date/xiezhixing/cDNA/AS001_S1_L001_1.fq.gz --cDNAfastq2 /date/xiezhixing/cDNA/AS001_S1_L001_2.fq.gz --oligofastq1 /date/xiezhixing/oligo/AS001_S1_L001_1.fq.gz --oligofastq2 /date/xiezhixing/oligo/AS001_S1_L001_2.fq.gz --genomeDir /date/xiezhixing --name as --threads 10
`
以下是报错
`[0;32;40mThe chemistry(darkreaction) automatically determined in cDNA : darkreaction[0m
[0;32;40mThe chemistry(darkreaction) automatically determined in oligoR1 : darkreaction[0m
[0;32;40mThe chemistry(darkreaction) automatically determined in oligoR2 : darkreaction[0m

2024-01-20 23:45:13
Processing cDNA library barcodes and aligning.

2024-01-20 23:45:13
Processing oligo library barcodes.
2024-01-20 23:45:48,781 - data - ERROR 
Command failed with exit code 1
2024-01-20 23:45:48,782 - data - ERROR 
2024-1-20  23:45:13 ..... started STAR run
Jan 20 23:45:13 ..... loading genome
Error code: SAW-A10151

2024-01-20 23:50:56
Annotating BAM files.
2024-01-20 23:50:56,850 - data - ERROR 
Command failed with exit code -11
2024-01-20 23:50:56,851 - data - ERROR 
[W::hts_set_opt] Cannot change block size for this format

2024-01-20 23:50:56,860 - data - ERROR 
Command failed with exit code 1
2024-01-20 23:50:56,860 - data - ERROR 
[E::hts_open_format] Failed to open file "/date/xiezhixing/as/01.data/final.bam" : No such file or directory
samtools sort: can't open "/date/xiezhixing/as/01.data/final.bam": No such file or directory

2024-01-20 23:50:56
Calculating bead similarity and merging beads.
`
`Traceback (most recent call last):
  File "/share/home/xiezhixing/miniconda3/envs/dnbc4tools/bin/dnbc4rna", line 8, in <module>
    sys.exit(main())
  File "/share/home/xiezhixing/miniconda3/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/rna/dnbc4rna.py", line 38, in main
    args.func(args)
  File "/share/home/xiezhixing/miniconda3/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/rna/count.py", line 220, in count
    Count(args).run()
  File "/share/home/xiezhixing/miniconda3/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/rna/count.py", line 58, in run
    from dnbc4tools.rna.src.oligo_filter import oligo_combine,cut_umi
  File "/share/home/xiezhixing/miniconda3/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/rna/src/oligo_filter.py", line 13, in <module>
    import polars as pl
ModuleNotFoundError: No module named 'polars'
Traceback (most recent call last):
  File "/share/home/xiezhixing/miniconda3/envs/dnbc4tools/bin/dnbc4tools", line 8, in <module>
    sys.exit(main())
  File "/share/home/xiezhixing/miniconda3/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/dnbc4tools.py", line 58, in main
    args.func(args)
  File "/share/home/xiezhixing/miniconda3/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/rna/run.py", line 105, in run
    Runpipe(args).runpipe()
  File "/share/home/xiezhixing/miniconda3/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/rna/run.py", line 92, in runpipe
    start_print_cmd(pipecmd,os.path.join(self.outdir,self.name))
  File "/share/home/xiezhixing/miniconda3/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/tools/utils.py", line 38, in start_print_cmd
    subprocess.check_call(arg, shell=True)
  File "/share/home/xiezhixing/miniconda3/envs/dnbc4tools/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'dnbc4rna count --name as --calling_method emptydrops --expectcells 3000 --forcecells 0 --minumi 1000 --threads 10 --outdir /date/xiezhixing' returned non-zero exit status 1.
`
这是我的存储文件对应的目录
![Snipaste_2024-01-21_11-09-34](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/115405260/2f40d88d-f9b8-4c58-b664-d624e92a1e88)
以上代码及文件是存储在服务器中调用并运行的
请问要如何解决呢

**Comment by owo12138** [comment]
是不是因为内存不够呢，我分配了300g内存。文件cDNA总共有80g大小

**Comment by lishuangshuang0616** [comment]
After looking at your directory, it seems that there is a problem with your mkref database. You can check whether there is an error when building the database.

**Comment by owo12138** [comment]
这是我利用quick start里面的人源基因组数据生成的ref.json
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/115405260/6f3dc45e-f98d-4fa7-bf97-1eac20223e09)
请问如何检查呢？

**Comment by lishuangshuang0616** [comment]
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/49019821/d1bb7d3a-735f-4a25-a0e5-0920b3ef3d69)
检查一下这些文件都有吗，红框框出来的

**Comment by owo12138** [comment]
都有的

**Comment by owo12138** [comment]
另外就是我考虑是dnbc4tools没安装完全的原因，我重新安装了，但是在安装过程一直报错

**Comment by owo12138** [comment]
安装完环境可以激活dnbc4tools环境， 但是无法调用dnbc4tools 显示no command

**Comment by owo12138** [comment]
报错如下
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/115405260/e50d500d-1231-4780-a4bd-a595c7e933e6)
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/115405260/1bffdc26-9207-4888-874a-904179f3d1d4)
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/115405260/79d114d8-d45d-42bf-b06f-94ae3248e978)
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/115405260/7ccf9805-300d-40f7-90b8-f20aa3db8864)

**Comment by lishuangshuang0616** [comment]
你这个是因为这个包无法安装，尝试在dnbc4tools.yaml开头几行修改下，给镜像试试
```
name: dnbc4tools
channels:
  - http://mirrors.bfsu.edu.cn/anaconda/pkgs/r/
  - http://mirrors.bfsu.edu.cn/anaconda/pkgs/main/
  - http://mirrors.bfsu.edu.cn/anaconda/pkgs/free/
  - http://mirrors.bfsu.edu.cn/anaconda/cloud/conda-forge/
  - http://mirrors.bfsu.edu.cn/anaconda/cloud/bioconda/
  - bioconda
  - conda-forge
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/
dependencies:
```

**Comment by lishuangshuang0616** [comment]
顺便截图下01.data内的cDNA_para、cDNAin1和cDNAin2的内容

**Comment by owo12138** [comment]
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/115405260/0458aead-5e4e-4164-822a-f9ee74b87ab4)
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/115405260/27da13df-2a65-443f-afc7-697a177eff21)
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/115405260/557b9250-98d2-4d10-86ee-53df59cdefc1)

**Comment by owo12138** [comment]
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/115405260/6332bfc7-8abc-4e81-b93a-3d6220d348a8)
现在用channel重新下载，仍然出现报错

**Comment by owo12138** [comment]
我试图更新这个yaml，但是又遇到以下报错
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/115405260/27731f64-ae17-4f98-a085-0e7ef77a039b)

**Comment by lishuangshuang0616** [comment]
把01.data内的cDNA_para、cDNAin1和cDNAin2文件发我吧
如果之前环境dnbc4tools 的command能使用，先不忙着安装了，这个包目前安装的镜像有点问题。

**Comment by owo12138** [comment]
重新安装一遍后的command也不能用了

**Comment by lishuangshuang0616** [comment]
原本的还在不

**Comment by owo12138** [comment]
comman和环境不在了，不过生成的数据还在

**Comment by lishuangshuang0616** [comment]
如果实在装不上，看下能否使用docker或者singularity试试

**Comment by owo12138** [comment]
[cDNAin1.zip](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/files/14019573/cDNAin1.zip)

**Comment by owo12138** [comment]
docker因为服务器无sudo权限，我试试singularity
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/115405260/702b1175-8eab-4cad-9351-8f5d2f977254)
请问singularity中的database 和data文件夹里面需要有什么呢

**Comment by lishuangshuang0616** [comment]
export只需要把你所有需要在容器中映射的目录放进去进行了，比如你的database的目录，你的文件目录，你的结果目录等等，只要需要挂载映射的都放上去进行

**Comment by owo12138** [comment]
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/115405260/6c1334ee-ed43-40ab-94be-b0cadd25d0d2)
但是似乎还是因为源的原因，这个singularity也下载不了

**Comment by owo12138** [comment]
于是我在自己windox电脑上加载wsl 运行docker
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/115405260/23a57b97-878f-4bea-ad5b-6638c47a1f41)
sh如上

![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/115405260/c44362b3-7cc8-4a14-b198-5c302e757658)
报错如上

![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/115405260/8b210b26-d2f5-47d3-8171-c9843abf0b47)
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/115405260/6e97b94f-ade3-415e-ae17-bd6dd068803a)
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/115405260/4b29fd61-d9b7-4dbb-a23d-b2f5ca7d2d7f)
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/115405260/a8673592-7ed2-4138-bb10-01697fea901f)
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/115405260/aca7fb99-68c9-4d89-afa3-29cbb7b0de81)
对应工作目录及对应文件如上

**Comment by lishuangshuang0616** [comment]
> 但是似乎还是因为源的原因，这个singularity也下载不了

多试几次呢？

**Comment by lishuangshuang0616** [comment]
docker的话你输入命令行呢，不用bash文件。

$Database_LOCAL:/database，直接替换$Database_LOCAL试试

**Comment by owo12138** [comment]
singularity我在两个服务器上运行了都是不行

**Comment by owo12138** [comment]
> docker的话你输入命令行呢，不用bash文件。
> 
> $Database_LOCAL:/database，直接替换$Database_LOCAL试试

那么我的路径应该如何输入呢？，这里我的路径应该替换在哪里呢？

**Comment by lishuangshuang0616** [comment]
docker run -P -v /mnt/d/scrna/dnbc4/Database:/database -v 
这样

**Comment by owo12138** [comment]
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/115405260/9a12da4a-82d6-429e-995c-3bf177b58e63)
我进行替换后仍然出现报错

**Comment by lishuangshuang0616** [comment]
没有问题，直接在rna后面加命令就行，如果不加命令就加--help

**Comment by owo12138** [comment]
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/115405260/109b9f2a-309c-46e2-95cd-60c333579974)
似乎还是不行？

**Comment by lishuangshuang0616** [comment]
你的文件需要路径，你挂在后的路径比如/database/genes.filter.gtf

**Comment by owo12138** [comment]
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/115405260/c471653c-d68c-4cfd-924e-b7975e4a2ece)
似乎仍然不可以

**Comment by owo12138** [comment]
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/115405260/6550cc22-131f-454a-86c3-7cc148fa2975)
我两种都试过了之前

**Comment by lishuangshuang0616** [comment]
你需要确定/mnt/d/scrna/dnbc4/Database目录内存在gtf文件且不是链接文件

**Comment by ultraypy** [comment]
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/56919476/6194c7b0-ecf7-4db1-ba50-4b2abfdab833)

**Comment by Wu123453234** [comment]
Can you help me see what caused this? There is no error log, the error was reported at the beginning, and the other data was still good yesterday, and the memory was enough.

Traceback (most recent call last):
  File "/home/bioyongjie/mambaforge/envs/dnbc4tools/bin/dnbc4tools", line 8, in <module>
    sys.exit(main())
  File "/home/bioyongjie/mambaforge/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/dnbc4tools.py", line 110, in main
    args.func(args)
  File "/home/bioyongjie/mambaforge/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/rna/data.py", line 169, in data
    Data(args).run()
  File "/home/bioyongjie/mambaforge/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/rna/data.py", line 87, in run
    cDNAconfig, oligoconfig = self.seqStructure()
  File "/home/bioyongjie/mambaforge/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/rna/data.py", line 35, in seqStructure
    oligoconfiglist = designated_chem_dark(
  File "chemistydark.py", line 444, in dnbc4tools.tools.chemistydark.designated_chem_dark
  File "chemistydark.py", line 265, in dnbc4tools.tools.chemistydark.check_fastqlist
  File "chemistydark.py", line 85, in dnbc4tools.tools.chemistydark.check_fastq_chemistry
  File "chemistydark.py", line 86, in genexpr
  File "chemistydark.py", line 86, in genexpr
  File "pysam/libcfaidx.pyx", line 651, in pysam.libcfaidx.FastxFile.__next__
ValueError: truncated quality string in /home/bioyongjie/dnbc4tools_dataprocess/gxf_0011_1203/oligo/L01_1.fq.gz
Traceback (most recent call last):
  File "/home/bioyongjie/mambaforge/envs/dnbc4tools/bin/dnbc4tools", line 8, in <module>
    sys.exit(main())
  File "/home/bioyongjie/mambaforge/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/dnbc4tools.py", line 110, in main
    args.func(args)
  File "/home/bioyongjie/mambaforge/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/rna/run.py", line 144, in run
    Runpipe(args).runpipe()
  File "/home/bioyongjie/mambaforge/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/rna/run.py", line 131, in runpipe
    start_print_cmd(pipecmd,os.path.join(self.outdir,self.name))
  File "/home/bioyongjie/mambaforge/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/tools/utils.py", line 138, in start_print_cmd
    subprocess.check_call(arg, shell=True)
  File "/home/bioyongjie/mambaforge/envs/dnbc4tools/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/home/bioyongjie/mambaforge/envs/dnbc4tools/bin/dnbc4tools rna data --cDNAfastq1 ./cDNA/L05_1.fq.gz,./cDNA/L06_1.fq.gz,./cDNA/L07_1.fq.gz,./cDNA/L08_1.fq.gz --cDNAfastq2 ./cDNA/L05_2.fq.gz,./cDNA/L06_2.fq.gz,./cDNA/L07_2.fq.gz,./cDNA/L08_2.fq.gz --oligofastq1 ./oligo/L01_1.fq.gz,./oligo/L02_1.fq.gz,./oligo/L03_1.fq.gz,./oligo/L04_1.fq.gz --oligofastq2 ./oligo/L01_2.fq.gz,./oligo/L02_2.fq.gz,./oligo/L03_2.fq.gz,./oligo/L04_2.fq.gz --threads 16 --name gxf_0011_1203 --chemistry auto --darkreaction auto --outdir /home/bioyongjie/dnbc4tools_dataprocess/gxf_0011_1203/result --genomeDir /home/bioyongjie/dnbc4tools_reference --gtf /home/bioyongjie/dnbc4tools_reference/genes.filter.gtf --chrMT chrM' returned non-zero exit status 1.
