### ISSUE TITLE
Error in .local(m, ...) :    insufficient unique points for computing knee/inflection points

### ISSUE THREAD

**Issue by Jylab-Genetics** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#63]
The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

Error in .local(m, ...) : 
  insufficient unique points for computing knee/inflection points
Calls: barcodeRanks -> barcodeRanks -> .local
Execution halted
Traceback (most recent call last):
  File "/storage/public/home/2021060213/anaconda3/envs/DNBC4tools_LFN/bin/DNBC4tools", line 8, in <module>
    sys.exit(main())
  File "/storage/public/home/2021060213/anaconda3/envs/DNBC4tools_LFN/lib/python3.8/site-packages/DNBC4tools/DNBC4tools.py", line 43, in main
    args.func(args)
  File "/storage/public/home/2021060213/anaconda3/envs/DNBC4tools_LFN/lib/python3.8/site-packages/DNBC4tools/tools/count.py", line 72, in count
    Count(args).run()
  File "/storage/public/home/2021060213/anaconda3/envs/DNBC4tools_LFN/lib/python3.8/site-packages/DNBC4tools/tools/count.py", line 55, in run
    logging_call(cellCalling_cmd,'count',self.outdir)
  File "/storage/public/home/2021060213/anaconda3/envs/DNBC4tools_LFN/lib/python3.8/site-packages/DNBC4tools/tools/utils.py", line 50, in logging_call
    check_call(popenargs,shell=True)
  File "/storage/public/home/2021060213/anaconda3/envs/DNBC4tools_LFN/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/storage/public/home/2021060213/anaconda3/envs/DNBC4tools_LFN/bin/Rscript /storage/public/home/2021060213/anaconda3/envs/DNBC4tools_LFN/lib/python3.8/site-packages/DNBC4tools/rna/cell_calling.R --matrix /storage/public/home/2021060213/Placenta_Single_Rowdata/data/Rawdata/C4-4-TP/C4-4-TP/01.data/raw_matrix --outdir /storage/public/home/2021060213/Placenta_Single_Rowdata/data/Rawdata/C4-4-TP/C4-4-TP/02.count/ --method emptydrops --expectcells 3000 --forcecells 0 --minumi 500' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/storage/public/home/2021060213/anaconda3/envs/DNBC4tools_LFN/bin/DNBC4tools", line 8, in <module>
    sys.exit(main())
  File "/storage/public/home/2021060213/anaconda3/envs/DNBC4tools_LFN/lib/python3.8/site-packages/DNBC4tools/DNBC4tools.py", line 43, in main
    args.func(args)
  File "/storage/public/home/2021060213/anaconda3/envs/DNBC4tools_LFN/lib/python3.8/site-packages/DNBC4tools/tools/run.py", line 79, in run
    Runpipe(args).runpipe()
  File "/storage/public/home/2021060213/anaconda3/envs/DNBC4tools_LFN/lib/python3.8/site-packages/DNBC4tools/tools/run.py", line 71, in runpipe
    start_print_cmd(pipecmd)
  File "/storage/public/home/2021060213/anaconda3/envs/DNBC4tools_LFN/lib/python3.8/site-packages/DNBC4tools/tools/utils.py", line 31, in start_print_cmd
    check_call(arg,shell=True)
  File "/storage/public/home/2021060213/anaconda3/envs/DNBC4tools_LFN/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'DNBC4tools count --name C4-4-TP --raw_matrix /storage/public/home/2021060213/Placenta_Single_Rowdata/data/Rawdata/C4-4-TP/C4-4-TP/01.data/raw_matrix --bam /storage/public/home/2021060213/Placenta_Single_Rowdata/data/Rawdata/C4-4-TP/C4-4-TP/01.data/final_sorted.bam --calling_method emptydrops --expectcells 3000 --forcecells 0 --minumi 500 --cDNAbarcodeCount /storage/public/home/2021060213/Placenta_Single_Rowdata/data/Rawdata/C4-4-TP/C4-4-TP/01.data/cDNA_barcode_counts_raw.txt --Indexreads /storage/public/home/2021060213/Placenta_Single_Rowdata/data/Rawdata/C4-4-TP/C4-4-TP/01.data/Index_reads.fq.gz --oligobarcodeCount /storage/public/home/2021060213/Placenta_Single_Rowdata/data/Rawdata/C4-4-TP/C4-4-TP/01.data/Index_barcode_counts_raw.txt --thread 10 --oligotype /storage/public/home/2021060213/anaconda3/envs/DNBC4tools_LFN/lib/python3.8/site-packages/DNBC4tools/config/oligo_type8.txt --outdir /storage/public/home/2021060213/Placenta_Single_Rowdata/data/Rawdata/C4-4-TP' returned non-zero exit status 1.

$cat 04DNBC4tools_map.sh
source /storage/public/home/2021060213/anaconda3/envs/DNBC4tools_LFN/bin/activate
DNBC4tools  run \
             --cDNAfastq1 /storage/public/home/2021060213/Placenta_Single_Rowdata/data/Rawdata/C4-4-TP/3092-1-230426/cDNA-3092-1-230426/FP200008583_L01_52_1.fq.gz \
             --cDNAfastq2 /storage/public/home/2021060213/Placenta_Single_Rowdata/data/Rawdata/C4-4-TP/3092-1-230426/cDNA-3092-1-230426/FP200008583_L01_52_2.fq.gz \
             --oligofastq1 /storage/public/home/2021060213/Placenta_Single_Rowdata/data/Rawdata/C4-4-TP/3092-1-230426/oligo-3092-1-230426/DP8450008182TL_L01_61_1.fq.gz \
             --oligofastq2 /storage/public/home/2021060213/Placenta_Single_Rowdata/data/Rawdata/C4-4-TP/3092-1-230426/oligo-3092-1-230426/DP8450008182TL_L01_61_2.fq.gz \
             --starIndexDir /storage/public/home/2021060213/Placenta_Single_Rowdata/data/Rawdata/C4-4-TP/_STARtmp \
	     --gtf /storage/public/home/2021060213/Placenta_Single_Rowdata/data/Rawdata/Genome/cow/genomic.gtf \
             --name C4-4-TP \
             --species Bos_taurus \
	     --thread 10 \
             --outdir /storage/public/home/2021060213/Placenta_Single_Rowdata/data/Rawdata/C4-4-TP

**Comment by lishuangshuang0616** [comment]
The inflection point cannot be found during analysis. Can you check the size of your bam or the size of the files in the raw_matrix directory?

**Comment by Jylab-Genetics** [comment]
| |
谭光辉（GuangHui-Tan）
西北农林科技大学动物科技学院，Northwest A&F University
17585473094
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 3/28/2024 17:49 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software] Error in .local(m, ...) : insufficient unique points for computing knee/inflection points (Issue #63) |

The inflection point cannot be found during analysis. Can you check the size of your bam or the size of the files in the raw_matrix directory?

**Comment by Jylab-Genetics** [comment]
> The inflection point cannot be found during analysis. Can you check the size of your bam or the size of the files in the raw_matrix directory?

final_sorted.bam  67.36GB

barcodes.tsv.gz 296KB  features.tsv.gz 1KB  matrix.mtx.gz 255KB

**Comment by lishuangshuang0616** [comment]
There seems to be something wrong with your raw_matrix.
Check 01.data/alignment_report.csv and 01.data/anno_report.csv

**Comment by zvittorio** [comment]
Hi! 

I am getting the same error, but in my case I can't find the raw_matrix anywhere, so I guess it didn't even get to that step. 
Moreover, the pipeline is being suspiciously fast, regardless of the size of the input. Indeed, all files it produced are basically empty (e.g. the BAM file). 
And this is the content of result_dir/report/alignment_report.csv : 

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">

<html>


<body>

Raw reads | 0
-- | --
Mapped reads | 0 (-nan%)
Mapped reads (paired) | 0
Properly paired reads | 0
Singleton reads | 0
Read 1 | 0
Read 2 | 0
Paired reads map on diff chr | 0
Plus strand | 0
Minus strand | 0
Mapping quals above 10 | 0
Mitochondria ratio | -nan%
Usable reads (ratio) | 0 (-nan%)
Failed to parse reads | 0


</body>

</html>

What could have gone wrong? 
Thanks for helping

Vittorio

**Comment by lishuangshuang0616** [comment]
Your version is too old. Which version is it? I don't recall the results being in this format. Based on this mapping, it appears there might be no data. Could it have been filtered out by the cDNA whitelist filtering? You might want to check this. If it doesn't affect your overall project analysis, you could also try analyzing with the current version. @zvittorio
