### ISSUE TITLE
Exception: The chemistry and darkreaction are unable to be automatically determined.

### ISSUE THREAD

**Issue by Xxhongs** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#76]
您好，在进行Chemistry(darkreaction) determined in oligoR2 : darkreaction步骤时，出现以下错误，我注意到帮助文档中提示了“If automatic identification fails or is incorrect, manual settings can be applied using --chemistry and --darkreaction. The --chemistry option includes "scRNAv1HT", "scRNAv2HT", and "scRNAv3HT", while the --darkreaction option uses commas to separate cDNA and oligo settings, such as "R1,R1R2", "R1,R1", "unset,unset", etc., where "R1,R1R2" indicates a dark reaction set for cDNA R1 and oligo R1R2”。您能具体解释一下该如何确定具体的--darkreaction option和--chemistry option吗？
值得注意的是，使用同样代码处理同批的其他数据能正常运行。

Chemistry(darkreaction) determined in oligoR1 : darkreaction
Chemistry(darkreaction) determined in oligoR2 : darkreaction
Valid chemistry read counts percent < 0.5
Traceback (most recent call last):
  File "/public//soft/Miniconda/envs/DNBC4toolsV2/bin/dnbc4tools", line 8, in <module>
    sys.exit(main())
  File "/public//soft/Miniconda/envs/DNBC4toolsV2/lib/python3.8/site-packages/dnbc4tools/dnbc4tools.py", line 110, in main
    args.func(args)
  File "/public//soft/Miniconda/envs/DNBC4toolsV2/lib/python3.8/site-packages/dnbc4tools/rna/data.py", line 169, in data
    Data(args).run()
  File "/public//soft/Miniconda/envs/DNBC4toolsV2/lib/python3.8/site-packages/dnbc4tools/rna/data.py", line 87, in run
    cDNAconfig, oligoconfig = self.seqStructure()
  File "/public//soft/Miniconda/envs/DNBC4toolsV2/lib/python3.8/site-packages/dnbc4tools/rna/data.py", line 55, in seqStructure
    cDNAconfig = designated_chem_dark(
  File "chemistydark.py", line 371, in dnbc4tools.tools.chemistydark.designated_chem_dark
  File "chemistydark.py", line 265, in dnbc4tools.tools.chemistydark.check_fastqlist
  File "chemistydark.py", line 102, in dnbc4tools.tools.chemistydark.check_fastq_chemistry
Exception: The chemistry and darkreaction are unable to be automatically determined.

Traceback (most recent call last):
  File "/public//soft/Miniconda/envs/DNBC4toolsV2/bin/dnbc4tools", line 8, in <module>
    sys.exit(main())
  File "/public//soft/Miniconda/envs/DNBC4toolsV2/lib/python3.8/site-packages/dnbc4tools/dnbc4tools.py", line 110, in main
    args.func(args)
  File "/public//soft/Miniconda/envs/DNBC4toolsV2/lib/python3.8/site-packages/dnbc4tools/rna/run.py", line 144, in run
    Runpipe(args).runpipe()
  File "/public//soft/Miniconda/envs/DNBC4toolsV2/lib/python3.8/site-packages/dnbc4tools/rna/run.py", line 131, in runpipe
    start_print_cmd(pipecmd,os.path.join(self.outdir,self.name))
  File "/public//soft/Miniconda/envs/DNBC4toolsV2/lib/python3.8/site-packages/dnbc4tools/tools/utils.py", line 138, in start_print_cmd
    subprocess.check_call(arg, shell=True)
  File "/public//soft/Miniconda/envs/DNBC4toolsV2/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/public//soft/Miniconda/envs/DNBC4toolsV2/bin/dnbc4tools rna data --cDNAfastq1 cDNA/E150019379_L01_79_1.fq.gz,cDNA/E150019379_L01_87_1.fq.gz,cDNA/E150019379_L01_95_1.fq.gz,cDNA/E150019379_L01_79_2.fq.gz,cDNA/E150019379_L01_87_2.fq.gz,cDNA/E150019379_L01_95_2.fq.gz --cDNAfastq2 cDNA/E150019379_L01_79_1.fq.gz,cDNA/E150019379_L01_87_1.fq.gz,cDNA/E150019379_L01_95_1.fq.gz,cDNA/E150019379_L01_79_2.fq.gz,cDNA/E150019379_L01_87_2.fq.gz,cDNA/E150019379_L01_95_2.fq.gz --oligofastq1 oligo/558_oligo_1.fq.gz --oligofastq2 oligo/558_oligo_2.fq.gz --threads 10 --name 558 --chemistry auto --darkreaction auto --outdir /public2/data/wangjunhao/data/MGI_SingCell/HT_scRNA-analysis/Vesion2/result --genomeDir /public//reference/hg38/MGI/DNBelab_C_Series_HT_scRNA/GRCh38V2 --gtf /public//reference/hg38/MGI/DNBelab_C_Series_HT_scRNA/GRCh38V2/genes.filter.gtf --chrMT chrM' returned non-zero exit status 1.

**Comment by lishuangshuang0616** [comment]
```
--cDNAfastq1 cDNA/E150019379_L01_79_1.fq.gz,cDNA/E150019379_L01_87_1.fq.gz,cDNA/E150019379_L01_95_1.fq.gz,cDNA/E150019379_L01_79_2.fq.gz,cDNA/E150019379_L01_87_2.fq.gz,cDNA/E150019379_L01_95_2.fq.gz
--cDNAfastq2 cDNA/E150019379_L01_79_1.fq.gz,cDNA/E150019379_L01_87_1.fq.gz,cDNA/E150019379_L01_95_1.fq.gz,cDNA/E150019379_L01_79_2.fq.gz,cDNA/E150019379_L01_87_2.fq.gz,cDNA/E150019379_L01_95_2.fq.gz
```
Are the fastqs not correctly?
Correct like this.
```
--cDNAfastq1 cDNA/E150019379_L01_79_1.fq.gz,cDNA/E150019379_L01_87_1.fq.gz,cDNA/E150019379_L01_95_1.fq.gz
--cDNAfastq2 cDNA/E150019379_L01_79_2.fq.gz,cDNA/E150019379_L01_87_2.fq.gz,cDNA/E150019379_L01_95_2.fq.gz
```

**Comment by Xxhongs** [comment]
原来是这么简单的错误，非常感谢！
