### ISSUE TITLE
ImportError:undefined symbol: BrotliSharedDictionaryDestroyInstance

### ISSUE THREAD

**Issue by jiangjasson** [MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software#84]
你好，我在运行run步骤遇到了问题
这是我的运行代码
`(dnbc4tools) dell@dell-Precision-7920-Tower:~/Documents/jiangss/script/dnbc4toolsscript$ cat 2.dnbc4tools_rna_run.sh` 
  
`dnbc4tools rna run --cDNAfastq1 /mnt/disk1/dataset/H1-ASCL1-Clone4-PNEC/rawdata/cDNA/H1Ascl1clone4_S1_L001_1.fq.gz --cDNAfastq2 /mnt/disk1/dataset/H1-ASCL1-Clone4-PNEC/rawdata/cDNA/H1Ascl1clone4_S1_L001_2.fq.gz --oligofastq1 /mnt/disk1/dataset/H1-ASCL1-Clone4-PNEC/rawdata/oligo/H1Ascl1clone4_S1_L001_1.fq.gz --oligofastq2 /mnt/disk1/dataset/H1-ASCL1-Clone4-PNEC/rawdata/oligo/H1Ascl1clone4_S1_L001_2.fq.gz --genomeDir /home/dell/Documents/jiangss/reference/dnbc4-genome/GRCh38-gencodev46-mCherry708 --name H1ASCL1PNEC --threads 90 1>dncbrnarun.log 2>&1`

我看了下报错的内容，是**ImportError: /home/dell/anaconda3/envs/dnbc4tools/lib/python3.8/site-packages/pyarrow/../../.././libbrotlidec.so.1: undefined symbol: BrotliSharedDictionaryDestroyInstance**

以下是具体的报错内容：
[0;32;40mChemistry(darkreaction) determined in oligoR1 : darkreaction[0m
[0;32;40mChemistry(darkreaction) determined in oligoR2 : darkreaction[0m
[0;32;40mChemistry(darkreaction) determined in cDNAR1 : darkreaction[0m

2024-06-26 09:34:31
Conduct quality control for cDNA library barcoding, perform alignment.

2024-06-26 09:34:31
Perform quality control for oligo library barcodes.

2024-06-26 10:32:24
Annotate gene regions for the aligned BAM.
Traceback (most recent call last):
  File "/home/dell/anaconda3/envs/dnbc4tools/bin/dnbc4tools", line 8, in <module>
    sys.exit(main())
  File "/home/dell/anaconda3/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/dnbc4tools.py", line 110, in main
    args.func(args)
  File "/home/dell/anaconda3/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/rna/data.py", line 169, in data
    Data(args).run()
  File "/home/dell/anaconda3/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/rna/data.py", line 157, in run
    oligo_combine_pl(f"{__root_dir__}/config/cellbarcode/oligo_type.json",
  File "/home/dell/anaconda3/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/tools/utils.py", line 183, in wrapper
    result = func(*args, **kwargs)
  File "oligo_filter.py", line 355, in dnbc4tools.rna.src.oligo_filter.oligo_combine_pl
  File "oligo_filter.py", line 280, in dnbc4tools.rna.src.oligo_filter.OligoCombiner.polars_CBUB
  File "/home/dell/anaconda3/envs/dnbc4tools/lib/python3.8/site-packages/polars/dataframe/frame.py", line 2238, in to_pandas
    record_batches = self._df.to_pandas()
  File "/home/dell/anaconda3/envs/dnbc4tools/lib/python3.8/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
ImportError: /home/dell/anaconda3/envs/dnbc4tools/lib/python3.8/site-packages/pyarrow/../../.././libbrotlidec.so.1: undefined symbol: BrotliSharedDictionaryDestroyInstance
Traceback (most recent call last):
  File "/home/dell/anaconda3/envs/dnbc4tools/bin/dnbc4tools", line 8, in <module>
    sys.exit(main())
  File "/home/dell/anaconda3/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/dnbc4tools.py", line 110, in main
    args.func(args)
  File "/home/dell/anaconda3/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/rna/run.py", line 144, in run
    Runpipe(args).runpipe()
  File "/home/dell/anaconda3/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/rna/run.py", line 131, in runpipe
    start_print_cmd(pipecmd,os.path.join(self.outdir,self.name))
  File "/home/dell/anaconda3/envs/dnbc4tools/lib/python3.8/site-packages/dnbc4tools/tools/utils.py", line 138, in start_print_cmd
    subprocess.check_call(arg, shell=True)
  File "/home/dell/anaconda3/envs/dnbc4tools/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/home/dell/anaconda3/envs/dnbc4tools/bin/dnbc4tools rna data --cDNAfastq1 /mnt/disk1/dataset/H1-ASCL1-Clone4-PNEC/rawdata/cDNA/H1Ascl1clone4_S1_L001_1.fq.gz --cDNAfastq2 /mnt/disk1/dataset/H1-ASCL1-Clone4-PNEC/rawdata/cDNA/H1Ascl1clone4_S1_L001_2.fq.gz --oligofastq1 /mnt/disk1/dataset/H1-ASCL1-Clone4-PNEC/rawdata/oligo/H1Ascl1clone4_S1_L001_1.fq.gz --oligofastq2 /mnt/disk1/dataset/H1-ASCL1-Clone4-PNEC/rawdata/oligo/H1Ascl1clone4_S1_L001_2.fq.gz --threads 90 --name H1ASCL1PNEC --chemistry auto --darkreaction auto --outdir /home/dell/Documents/jiangss/project/H1-Ascl1-mCherry-clone4 --genomeDir /home/dell/Documents/jiangss/reference/dnbc4-genome/GRCh38-gencodev46-mCherry708 --gtf /home/dell/Documents/jiangss/reference/GencodeRef/DNBC4_format/gencode.v46.primary_assembly.annotation.filter.mCherry.gtf --chrMT chrM' returned non-zero exit status 1.

我是从Gencode下载fasta和gtf文件，往里面加了一个荧光基因，然后生成了参考基因组，这一步没有报错，成功生成了，在run这一步报错结束时，生成的**01.data**文件如下：
![Screenshot from 2024-06-26 15-46-26](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/42676666/c89140ee-3759-4ec1-87f6-b16aec81d953)

log目录的文件:
[20240626.txt](https://github.com/user-attachments/files/15984747/20240626.txt)
[bt_log.txt](https://github.com/user-attachments/files/15984753/bt_log.txt)

这是我的conda环境中的包：
[conda_list.txt](https://github.com/user-attachments/files/15984773/conda_list.txt)

请问要如何解决呢?

**Comment by jiangjasson** [comment]
我查看了下dnbc4tools环境中的`brotli`的版本，显示没有，在base环境中有
![SmartSelect_20240626_165726_Termius](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/42676666/d3436f66-f0ce-44b7-82df-1643e499abe4)

**Comment by lishuangshuang0616** [comment]
好像是你的base与环境里面的这个so冲突了。能否删除这个环境，重新使用过这个方法安装而不是yaml呢
![image](https://github.com/MGI-tech-bioinformatics/DNBelab_C_Series_HT_scRNA-analysis-software/assets/49019821/03a6b878-48a5-4524-8c5c-1eeb8c9beebf)

**Comment by jiangjasson** [comment]
> 好像是你的base与环境里面的这个so冲突了。能否删除这个环境，重新使用过这个方法安装而不是yaml呢 ![image](https://private-user-images.githubusercontent.com/49019821/343095827-03a6b878-48a5-4524-8c5c-1eeb8c9beebf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NTEzMTEsIm5iZiI6MTcxOTQ1MTAxMSwicGF0aCI6Ii80OTAxOTgyMS8zNDMwOTU4MjctMDNhNmI4NzgtNDhhNS00NTI0LThjNWMtMWVlYjhjOWJlZWJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDAxMTY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhOTkyNGJhYWU1ZmY1NzA5NDdmNDY0YTNhNTU2YmViOTYyYmE0ODg3NWY3ZTYzZWY1MjcyYmRhMDBmZDIyMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a1Vg825UghuaJm-xV9xY3n1JRTyn9qe-z-_pfv1fNvs)

非常感谢，删除环境后，不使用yaml重装，就没报错了
